### ISSUE TITLE
Shortcode for Youtube

### ISSUE THREAD

**Issue by integrationtfo** [ableplayer/ableplayer-wordpress#1]
Hello,

I try to use the shortcode for a Youtube link but it doesn't display, I know it accepts multiple file extensions but not sure if Youtube works with it. Do you have an example link by any chance ?

Thank you !

**Comment by terrill** [comment]
@integrationtfo this WordPress plug-in currently doesn't support shortcodes - it just enables you to run Able Player by entering HTML. I don't have a public demo of that running within WordPress - just the simple Able Player demos that accompany the main Able Player repo.  

I'm hoping to build a more robust WordPress plug-in in the near future. Meanwhile, what code are you entering exactly?  Also, which version of WordPress?  Do you have a public URL where I can have a look?

**Comment by integrationtfo** [comment]
Hello Terill,

Thank you for your quick reply ! 

Actually my team is trying to implement accessible videos from Youtube on our Wordpress websites, we actually don't have any public URL, we all are testing locally this plugin. We have editors who want to add Youtube videos on their articles, of course, they're not developers so we want them to use a simple ableplayer shortcode where you just retrieve the video id as : 
[ableplayer youtube-video-id="xxxx"]

We're using the Wordpress version 4.9.4

Thank you for your help !

**Comment by terrill** [comment]
This is now fixed with version 1.0, which is now an official release on the [WordPress Plugins](https://wordpress.org/plugins/ableplayer/) site. 

Please see the documentation for details. In particular, the shortcode for adding YouTube is: 
`[ableplayer youtube-id="XXXXXXXXXXX"]` (not `youtube-video-id`).
