### ISSUE TITLE
Videos not playing on iphone

### ISSUE THREAD

**Issue by ellinika** [ableplayer/ableplayer-wordpress#7]
I'm using able player 1.0 plugin for WordPress. The videos are playing just fine on my desktop computer, but they aren't playing on my iPhone. It looks like they are stuck at buffering. Please help.

**Comment by terrill** [comment]
@ellinika please try the latest release (version 1.2.0). Does that solve the problem you're experiencing on iPhones?

**Comment by ellinika** [comment]
Done! Yes, problem solved. Thank you for updating the plugin!
