### ISSUE TITLE
Transcript Opens as a Dialog and when closed no way to open it back

### ISSUE THREAD

**Issue by digitala11y** [ableplayer/ableplayer-wordpress#9]
Hello,
Here is the demo video link,
https://www.digitala11y.com/academy/able-player-video-on-wordpress-demo/   The video transcript opens in a dialog below the video when navigating using screen reader, once the dialog is closed there is no way to trigger it. Is there some configuration we need to do so that transcript is presented below the video with the checkbox? I see this is not the case on wpaccessibility.day website, it works perfectly.

**Comment by joedolson** [comment]
@digitala11y Hi, Raghavendra! It looks to me, based on your demo page, that you've got this worked out; I'm going to close this issue, but feel free to comment again if it's still an issue.
